---
apiVersion: v1
kind: Service
metadata:
  labels:
    cattle.io/creator: norman
  name: {{APPNAME}}-loadbalancer
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: 8080tcp80803
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: deployment-qadeploy-{{APPNAME}}
    version: v{{BUILDNUMBER}}
  sessionAffinity: None
  type: LoadBalancer
